/**
 * Runs every probe against every adapter and writes the matrix.
 *
 *   bun conformance/run.ts                 replay from cache, fetch what is missing
 *   bun conformance/run.ts --refresh       ignore the cache and re-fetch everything
 *   bun conformance/run.ts --cached        never touch the network; fail if uncached
 *   bun conformance/run.ts --only ours     one adapter
 *   bun conformance/run.ts --base http://127.0.0.1:8787   point at a local instance
 *
 * Output: `results.json` for machines and `report.md` for people.
 */

import { allAdapters } from "./adapters/index.ts";
import { PROBES } from "./probes.ts";
import type { Adapter, Dimension, Probe, ProbeResult, Verdict } from "./types.ts";

const args = new Set(Bun.argv.slice(2));
const valueOf = (flag: string): string | null => {
  const index = Bun.argv.indexOf(flag);
  return index === -1 ? null : (Bun.argv[index + 1] ?? null);
};

const options = { cachedOnly: args.has("--cached"), refresh: args.has("--refresh") };
const only = valueOf("--only");
const ourBase = valueOf("--base") ?? "https://colophon.hellobensmith.workers.dev";

const adapters = allAdapters(options, ourBase).filter((a) => only === null || a.id === only);

interface Cell extends ProbeResult {
  readonly adapter: string;
  readonly probe: string;
}

const VERDICT_MARK: Readonly<Record<Verdict, string>> = {
  safe: "ok",
  unsafe: "**UNSAFE**",
  divergent: "differs",
  missing: "absent",
  "not-applicable": "n/a",
  unreachable: "—",
};

const DIMENSION_TITLES: Readonly<Record<Dimension, string>> = {
  "reference-resolution": "Reference resolution",
  "textual-integrity": "Textual integrity",
  "self-description": "Self-description",
  "wire-contract": "Wire contract",
};

async function runProbe(probe: Probe, adapter: Adapter): Promise<Cell> {
  const supported = probe.requires.some((capability) => adapter.capabilities.has(capability));
  if (!supported) {
    return {
      adapter: adapter.id,
      probe: probe.id,
      verdict: "not-applicable",
      summary: `does not offer ${probe.requires.join(" or ")}`,
      request: null,
      evidence: null,
    };
  }
  try {
    return { adapter: adapter.id, probe: probe.id, ...(await probe.run(adapter)) };
  } catch (error) {
    // A thrown adapter is a bug in the suite, never a finding about the API.
    return {
      adapter: adapter.id,
      probe: probe.id,
      verdict: "unreachable",
      summary: `suite error: ${(error as Error).message}`,
      request: null,
      evidence: null,
    };
  }
}

const cells: Cell[] = [];
for (const adapter of adapters) {
  process.stdout.write(`${adapter.name}\n`);
  for (const probe of PROBES) {
    const cell = await runProbe(probe, adapter);
    cells.push(cell);
    const mark = cell.verdict === "unsafe" ? "!" : cell.verdict === "safe" ? "." : "?";
    process.stdout.write(`  ${mark} ${probe.title.padEnd(32)} ${cell.summary}\n`);
  }
  process.stdout.write("\n");
}

/* ------------------------------------------------------------------ *
 * Report
 * ------------------------------------------------------------------ */

const find = (probeId: string, adapterId: string): Cell | undefined =>
  cells.find((c) => c.probe === probeId && c.adapter === adapterId);

const lines: string[] = [];
lines.push("# How Scripture APIs answer the same questions");
lines.push("");
lines.push(
  "Generated by `bun conformance/run.ts`. Each column is one public API; each row is " +
    "a question a caller would care about. Every API answers in its own dialect through " +
    "an adapter, so this is a map of what the ecosystem does — not a scorecard, and not " +
    "a pass/fail against any one implementation's endpoint shapes.",
);
lines.push("");
lines.push(
  "**This exists for transparency, not criticism.** Every project here is solving the " +
    "same problem without a shared contract to work from, and each arrived at reasonable " +
    "answers that happen not to agree. That is the cost of there being no agreed " +
    "semantics, and it is paid by the people building on top. The suite scores its own " +
    "author's API as a subject alongside the rest, and found a gap there too.",
);
lines.push("");
lines.push(
  "`n/a` means the API does not claim that capability — several take numeric book " +
    "identifiers and leave reference parsing to the client, which is a design choice, " +
    "not a defect. `differs` marks a defensible answer incompatible with another " +
    "defensible answer. **UNSAFE** marks the sharpest case: an answer a caller cannot " +
    "tell is wrong.",
);
lines.push("");
lines.push("## Subjects");
lines.push("");
lines.push("| API | Edition | Capabilities |");
lines.push("|---|---|---|");
for (const adapter of adapters) {
  lines.push(
    `| [${adapter.name}](${adapter.homepage}) | ${adapter.edition.toUpperCase()} | ${[...adapter.capabilities].join(", ")} |`,
  );
}
lines.push("");

for (const dimension of Object.keys(DIMENSION_TITLES) as Dimension[]) {
  const probes = PROBES.filter((p) => p.dimension === dimension);
  if (probes.length === 0) continue;
  lines.push(`## ${DIMENSION_TITLES[dimension]}`);
  lines.push("");
  lines.push(`| Question | ${adapters.map((a) => a.name).join(" | ")} |`);
  lines.push(`|---|${adapters.map(() => "---").join("|")}|`);
  for (const probe of probes) {
    const row = adapters.map((a) => {
      const cell = find(probe.id, a.id);
      return cell === undefined ? "—" : `${VERDICT_MARK[cell.verdict]}<br><sub>${cell.summary}</sub>`;
    });
    lines.push(`| **${probe.title}** | ${row.join(" | ")} |`);
  }
  lines.push("");
  for (const probe of probes) {
    lines.push(`*${probe.title}* — ${probe.rationale}`);
    lines.push("");
  }
}

/* The systemic observation comes before the individual ones: it is the reason
 * the individual ones exist, and it is nobody's fault in particular. */
const parsers = adapters.filter((a) => a.capabilities.has("freeform-reference"));
lines.push("## What this shows");
lines.push("");
lines.push(
  `Of the ${adapters.length} APIs measured, ${adapters.length - parsers.length} do no ` +
    "reference parsing at all — they take numeric book identifiers and leave it to the " +
    "caller. That is a legitimate choice, but it means every application built on them " +
    "reimplements book names, abbreviations, ranges and bounds checking, and each one " +
    "does it differently. Reference parsing is the single most duplicated piece of work " +
    "in this ecosystem, and the least shared.",
);
lines.push("");
lines.push(
  "Among those that do parse references, the answers to identical questions diverge " +
    "in ways a caller cannot see: whether an ambiguous abbreviation is refused or " +
    "guessed, whether a verse the translation omits comes back empty, bracketed, or " +
    "missing, whether a superscription is its own text or merged into verse 1.",
);
lines.push("");

const unsafe = cells.filter((c) => c.verdict === "unsafe");
lines.push("## Where a caller cannot tell");
lines.push("");
if (unsafe.length === 0) {
  lines.push("No API returned an answer a caller could not detect as wrong.");
} else {
  lines.push(
    `${unsafe.length} case${unsafe.length === 1 ? "" : "s"} where a request produced a ` +
      "plausible-looking answer that is not what was asked for. These are the sharpest " +
      "cost of having no shared contract, because nothing downstream can detect them:",
  );
  lines.push("");
  for (const cell of unsafe) {
    const adapter = adapters.find((a) => a.id === cell.adapter)!;
    const probe = PROBES.find((p) => p.id === cell.probe)!;
    lines.push(`- **${adapter.name}** — ${probe.title}: ${cell.summary}`);
    if (cell.request !== null) lines.push(`  - request: \`${cell.request}\``);
    if (cell.evidence !== null) lines.push(`  - returned: ${cell.evidence}`);
  }
}
lines.push("");

const counts = new Map<Verdict, number>();
for (const cell of cells) counts.set(cell.verdict, (counts.get(cell.verdict) ?? 0) + 1);
lines.push("## Totals");
lines.push("");
lines.push(`| Verdict | Count |`);
lines.push(`|---|---|`);
for (const [verdict, count] of [...counts].sort((a, b) => b[1] - a[1])) {
  lines.push(`| ${verdict} | ${count} |`);
}
lines.push("");

const here = new URL(".", import.meta.url).pathname;
await Bun.write(`${here}report.md`, `${lines.join("\n")}\n`);
await Bun.write(
  `${here}results.json`,
  `${JSON.stringify({ base: ourBase, adapters: adapters.map((a) => a.id), cells }, null, 2)}\n`,
);

console.log(`${cells.length} cells across ${adapters.length} APIs and ${PROBES.length} probes`);
console.log(
  [...counts].map(([verdict, count]) => `${verdict}: ${count}`).join("  |  "),
);
console.log(`\nwrote conformance/report.md and conformance/results.json`);
if (unsafe.length > 0) console.log(`\n${unsafe.length} unsafe behaviour(s) — see the report`);
