// GENERATED by scripts/build-data.ts — do not edit.
/**
 * What the text is. Derived from the source archive alone, so republishing
 * artifacts over unchanged source leaves it untouched. Anchors bind to this.
 */
export const REVISION_ID = "4744a308fd2531c6dc2fba4fa0e29886ff769d7a72bf34ad493874d268f069aa";

/**
 * What was published. Derived from the whole manifest, so a metadata-only
 * change mints a new generation over identical text.
 */
export const GENERATION_ID = "b0ce605636725d8cf24f40aa10894cc3f19e6bda6f258cc819134a880c23c66f";

export const EDITION_ID = "sblgnt";

// GENERATED by scripts/build-data.ts — do not edit.
/** Fingerprint of the corpus; changes whenever any verse or title changes. */
export const DATA_VERSION = "98932e542956";

/** Verse count per chapter, indexed from chapter 1, for each of the 66 books. */
export const VERSE_COUNTS: Readonly<Record<string, readonly number[]>> = {
  MAT: [25,23,17,25,48,34,29,34,38,42,30,50,58,36,39,28,26,34,30,34,46,46,38,51,46,75,66,20],
  MRK: [45,28,35,41,43,56,36,38,48,52,32,44,37,72,46,20],
  LUK: [80,52,38,44,39,49,50,56,62,42,54,59,35,35,32,31,36,43,48,47,38,71,55,53],
  JHN: [51,25,36,54,46,71,53,59,41,42,57,50,38,31,27,33,26,40,42,31,25],
  ACT: [26,47,26,37,42,15,60,39,43,48,30,25,52,28,40,40,34,28,40,38,40,30,35,26,27,32,44,30],
  ROM: [32,29,31,25,21,23,25,39,33,21,36,21,14,23,33,24],
  "1CO": [31,16,23,21,13,20,40,13,27,33,34,31,13,40,58,24],
  "2CO": [24,17,18,18,21,18,16,24,15,18,33,21,13],
  GAL: [24,21,29,31,26,18],
  EPH: [23,22,21,32,33,24],
  PHP: [30,30,21,23],
  COL: [29,23,25,18],
  "1TH": [10,20,13,18,28],
  "2TH": [12,17,18],
  "1TI": [20,15,16,16,25,21],
  "2TI": [18,26,17,22],
  TIT: [16,15,15],
  PHM: [25],
  HEB: [14,18,19,16,14,20,28,13,28,39,40,29,25],
  JAS: [27,26,18,17,20],
  "1PE": [25,25,22,19,14],
  "2PE": [21,22,18],
  "1JN": [10,29,24,21,21],
  "2JN": [13],
  "3JN": [15],
  JUD: [25],
  REV: [20,29,22,11,14,17,17,13,21,11,19,18,18,20,8,21,18,24,21,15,27,21],
};

/** Superscriptions printed above a chapter, keyed by "BOOK.CHAPTER". */
export const TITLES: Readonly<Record<string, string>> = {

};

/**
 * Lines printed below a chapter's last verse. USFX marks these with the same
 * <d> element as a superscription, so only position tells them apart.
 */
export const SUBSCRIPTIONS: Readonly<Record<string, string>> = {

};

/** Footnotes for the verses the ASV omits from its text. */
export const NOTES: Readonly<Record<string, string>> = {

};

/** Psalms whose superscription counts as Hebrew verse 1. */
export const TITLED_PSALMS: readonly number[] = [];
