/**
 * Build step: turn the ebible.org USFX release into embedded TypeScript modules.
 *
 * Emits three generated files under src/data/:
 *   text.ts         verse text as one blob plus base36 delta-encoded lengths
 *   search-index.ts inverted index, token -> base36 delta-encoded postings
 *   meta.ts         per-chapter verse counts, titles, notes, Hebrew offsets
 *
 * Nothing is written unless every assertion in src/validate.ts passes.
 */

import { createHash } from "node:crypto";

import { parseUsfx, type UsfxDocument } from "../src/usfx.ts";
import { validateCorpus, ValidationError } from "../src/validate.ts";
import { PROTESTANT_ORDER } from "../src/canon.ts";
import { buildFamilies } from "../src/morphology.ts";
import { downloadWithResume, expectedSize, DownloadError } from "./download.ts";

const SOURCE_URL = "https://ebible.org/Scriptures/eng-asv_usfx.zip";
const CACHE_DIR = new URL("../.cache/", import.meta.url).pathname;
const ZIP_PATH = `${CACHE_DIR}eng-asv_usfx.zip`;
const XML_PATH = `${CACHE_DIR}eng-asv_usfx.xml`;
const DATA_DIR = new URL("../src/data/", import.meta.url).pathname;

async function download(): Promise<void> {
  const existing = Bun.file(ZIP_PATH);
  const expected = await expectedSize(SOURCE_URL, fetch);
  if ((await existing.exists()) && existing.size === expected) {
    console.log(`  cached  ${expected.toLocaleString()} bytes`);
    return;
  }
  const bytes = await downloadWithResume(SOURCE_URL, {
    onProgress: (received, total, attempt) => {
      console.log(`  attempt ${attempt}: ${received.toLocaleString()} / ${total.toLocaleString()}`);
    },
  });
  await Bun.write(ZIP_PATH, bytes);
}

async function extract(): Promise<string> {
  const cached = Bun.file(XML_PATH);
  if (!(await cached.exists())) {
    const unzip = Bun.spawn(["unzip", "-o", "-q", ZIP_PATH, "eng-asv_usfx.xml", "-d", CACHE_DIR], {
      stderr: "pipe",
    });
    const code = await unzip.exited;
    if (code !== 0) {
      throw new Error(`unzip failed with code ${code}: ${await new Response(unzip.stderr).text()}`);
    }
  }
  return await Bun.file(XML_PATH).text();
}

/** Base36 delta encoding keeps the numeric payloads compact in the bundle. */
function encodeDeltas(values: readonly number[]): string {
  let previous = 0;
  const parts: string[] = [];
  for (const value of values) {
    parts.push((value - previous).toString(36));
    previous = value;
  }
  return parts.join(",");
}

const TOKEN_SPLIT = /[^a-z']+/;

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .split(TOKEN_SPLIT)
    .filter((token) => token.length >= 2);
}

function buildTextModule(doc: UsfxDocument): string {
  const blob = doc.verses.map((verse) => verse.text).join("");
  const lengths = doc.verses.map((verse) => verse.text.length);
  return `// GENERATED by scripts/build-data.ts — do not edit.
/** Every verse concatenated in canonical order, addressed by LENGTHS offsets. */
export const TEXT: string = ${JSON.stringify(blob)};

/** Base36 delta-encoded verse lengths; cumulative sums give slice boundaries. */
export const LENGTHS: string = ${JSON.stringify(encodeDeltas(lengths))};

export const VERSE_COUNT = ${doc.verses.length};
`;
}

function buildIndexModule(doc: UsfxDocument): string {
  const postings = new Map<string, number[]>();
  doc.verses.forEach((verse, sequence) => {
    const seen = new Set<string>();
    for (const token of tokenize(verse.text)) {
      if (seen.has(token)) continue;
      seen.add(token);
      let list = postings.get(token);
      if (list === undefined) {
        list = [];
        postings.set(token, list);
      }
      list.push(sequence);
    }
  });

  const lines = [...postings.entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([token, list]) => `${token}:${encodeDeltas(list)}`);

  const wordCounts = doc.verses.map((verse) => (verse.text === "" ? 0 : verse.text.split(" ").length));

  const frequencies = [...postings.entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([, list]) => list.length);

  return `// GENERATED by scripts/build-data.ts — do not edit.
/** Inverted index: one "token:base36DeltaPostings" entry per line. */
export const INDEX: string = ${JSON.stringify(lines.join("\n"))};

/**
 * Base36 delta-encoded posting count per token, in the same order as INDEX.
 * Lets a query weigh a term without decoding its postings.
 */
export const DOC_FREQUENCIES: string = ${JSON.stringify(encodeDeltas(frequencies))};

/** Base36 delta-encoded word count per verse, for BM25 length normalization. */
export const WORD_COUNTS: string = ${JSON.stringify(encodeDeltas(wordCounts))};

export const TOKEN_COUNT = ${lines.length};
`;
}

/**
 * A short, stable fingerprint of the corpus. It names the edge cache, so
 * regenerating the data automatically invalidates cached responses instead of
 * letting an `immutable` Cache-Control serve last year's text after a redeploy.
 */
function fingerprint(doc: UsfxDocument): string {
  const hash = createHash("sha256");
  for (const verse of doc.verses) {
    hash.update(verse.bcv);
    hash.update("\u0000");
    hash.update(verse.text);
    hash.update("\u0000");
  }
  for (const [key, title] of [...doc.titles].sort(([a], [b]) => (a < b ? -1 : 1))) {
    hash.update(`${key}=${title}\u0000`);
  }
  return hash.digest("hex").slice(0, 12);
}

/**
 * Word families are a pure function of the vocabulary, so they are computed here
 * rather than on every isolate start. Building them at runtime measured 14 ms
 * locally and several times that in production, against a bundle cost of a few
 * tens of kilobytes.
 */
function buildFamiliesModule(tokens: readonly string[]): string {
  const families = buildFamilies(tokens);
  const groups = new Map<string, readonly string[]>();
  for (const [, family] of families) groups.set(family.join(","), family);
  const lines = [...groups.keys()].sort();
  return `// GENERATED by scripts/build-data.ts — do not edit.
/** Morphological families, one comma-separated group per line. */
export const FAMILY_GROUPS: string = ${JSON.stringify(lines.join("\n"))};

export const FAMILY_COUNT = ${lines.length};
`;
}

function buildMetaModule(doc: UsfxDocument): string {
  const verseCounts = new Map<string, number[]>();
  for (const verse of doc.verses) {
    let chapters = verseCounts.get(verse.book);
    if (chapters === undefined) {
      chapters = [];
      verseCounts.set(verse.book, chapters);
    }
    chapters[verse.chapter - 1] = (chapters[verse.chapter - 1] ?? 0) + 1;
  }

  const countsLiteral = PROTESTANT_ORDER.map((bookId) => {
    const chapters = verseCounts.get(bookId);
    if (chapters === undefined) throw new Error(`No verses collected for ${bookId}`);
    return `  ${bookId.startsWith("1") || bookId.startsWith("2") || bookId.startsWith("3") ? `"${bookId}"` : bookId}: [${chapters.join(",")}],`;
  }).join("\n");

  const titlesLiteral = [...doc.titles.entries()]
    .map(([key, title]) => `  ${JSON.stringify(key)}: ${JSON.stringify(title)},`)
    .join("\n");

  const subscriptionsLiteral = [...doc.subscriptions.entries()]
    .map(([key, text]) => `  ${JSON.stringify(key)}: ${JSON.stringify(text)},`)
    .join("\n");

  const notesLiteral = doc.verses
    .filter((verse) => verse.note !== null)
    .map((verse) => `  ${JSON.stringify(verse.bcv)}: ${JSON.stringify(verse.note)},`)
    .join("\n");

  // A Psalm carrying a superscription numbers that title as Hebrew verse 1,
  // shifting every English verse up by one.
  const titledPsalms = [...doc.titles.keys()]
    .filter((key) => key.startsWith("PSA."))
    .map((key) => Number.parseInt(key.slice(4), 10))
    .sort((a, b) => a - b);

  return `// GENERATED by scripts/build-data.ts — do not edit.
/** Fingerprint of the corpus; changes whenever any verse or title changes. */
export const DATA_VERSION = ${JSON.stringify(fingerprint(doc))};

/** Verse count per chapter, indexed from chapter 1, for each of the 66 books. */
export const VERSE_COUNTS: Readonly<Record<string, readonly number[]>> = {
${countsLiteral}
};

/** Superscriptions printed above a chapter, keyed by "BOOK.CHAPTER". */
export const TITLES: Readonly<Record<string, string>> = {
${titlesLiteral}
};

/**
 * Lines printed below a chapter's last verse. USFX marks these with the same
 * <d> element as a superscription, so only position tells them apart.
 */
export const SUBSCRIPTIONS: Readonly<Record<string, string>> = {
${subscriptionsLiteral}
};

/** Footnotes for the verses the ASV omits from its text. */
export const NOTES: Readonly<Record<string, string>> = {
${notesLiteral}
};

/** Psalms whose superscription counts as Hebrew verse 1. */
export const TITLED_PSALMS: readonly number[] = [${titledPsalms.join(",")}];
`;
}

async function main(): Promise<void> {
  console.log("Downloading ASV USFX…");
  await download();

  console.log("Extracting…");
  const xml = await extract();

  console.log("Parsing…");
  const started = performance.now();
  const doc = parseUsfx(xml);
  console.log(
    `  ${doc.verses.length.toLocaleString()} verses, ${doc.books.length} books, ` +
      `${doc.titles.size} titles in ${(performance.now() - started).toFixed(0)} ms`,
  );

  console.log("Validating…");
  validateCorpus(doc);
  console.log("  all assertions passed");

  console.log("Emitting data modules…");
  await Bun.write(`${DATA_DIR}text.ts`, buildTextModule(doc));
  const indexModule = buildIndexModule(doc);
  await Bun.write(`${DATA_DIR}search-index.ts`, indexModule);
  await Bun.write(`${DATA_DIR}meta.ts`, buildMetaModule(doc));

  // Families are derived from the vocabulary the index just recorded.
  const tokens = [...new Set(
    doc.verses.flatMap((verse) => tokenize(verse.text)),
  )].sort();
  await Bun.write(`${DATA_DIR}families.ts`, buildFamiliesModule(tokens));

  for (const name of ["text.ts", "search-index.ts", "meta.ts", "families.ts"]) {
    const file = Bun.file(`${DATA_DIR}${name}`);
    console.log(`  src/data/${name.padEnd(16)} ${(file.size / 1024 / 1024).toFixed(2)} MB`);
  }
}

try {
  await main();
} catch (error) {
  if (error instanceof ValidationError) {
    console.error(`\nIngestion aborted. ${error.message}`);
  } else if (error instanceof DownloadError) {
    console.error(`\nIngestion failed while downloading: ${error.message}`);
  } else {
    console.error(`\nIngestion failed: ${(error as Error).message}`);
  }
  process.exit(1);
}
