/**
 * Builds SBLGNT's critical apparatus into an embedded module — a separate
 * step from `build-data.ts`, because the apparatus isn't a Scripture text:
 * it's a collation of printed editions (WH, Tregelles, NA27/NA28, RP, and
 * occasionally others) keyed to verses, not a `ScriptureFormat` any other
 * edition could plausibly share. See `src/sblgnt-apparatus.ts` for the
 * parser and exactly what this data is (and isn't — no manuscripts).
 *
 *   bun run scripts/build-sblgnt-apparatus.ts \
 *     --source .cache/sblgntapp-xml --text-source .cache/sblgnt-xml
 *
 * Every apparatus verse reference is cross-checked by actually re-parsing
 * the real text source (not the generated VERSE_COUNTS, which is a
 * per-chapter total and undercounts the highest verse number in any
 * chapter with a declared omission) rather than trusted on faith.
 */
import { readdir } from "node:fs/promises";
import path from "node:path";

import { parseApparatusBook, mergeApparatus, type ApparatusNote } from "../src/sblgnt-apparatus.ts";
import { parseSblgnt } from "../src/sblgnt.ts";

function namedOverride(argv: readonly string[], flag: string): string {
  const index = argv.indexOf(flag);
  const value = index === -1 ? undefined : argv[index + 1];
  if (value === undefined || value.startsWith("--")) {
    throw new Error(`${flag} needs a path`);
  }
  return value;
}

async function main(): Promise<void> {
  const sourceDir = namedOverride(process.argv, "--source");
  const textDir = namedOverride(process.argv, "--text-source");
  const entries = (await readdir(sourceDir)).filter((name) => name.endsWith(".xml")).sort();
  if (entries.length === 0) {
    throw new Error(`${sourceDir} holds no .xml files.`);
  }

  console.log(`Reading ${entries.length} apparatus files from ${sourceDir}`);
  const books = await Promise.all(
    entries.map(async (name) => parseApparatusBook(await Bun.file(path.join(sourceDir, name)).text())),
  );
  const merged = mergeApparatus(books);

  let totalNotes = 0;
  for (const notes of merged.values()) totalNotes += notes.length;
  console.log(`  ${merged.size} verses, ${totalNotes} notes`);

  console.log("Cross-checking every reference against the real parsed text…");
  // Not VERSE_COUNTS: it's a per-chapter total, which undercounts the
  // highest verse number in any chapter with a declared omission (e.g. Acts
  // 15 has 40 verses present but its highest number is 41 — 15:34 is
  // missing). The real verse set, gaps and all, is the only correct ceiling.
  const textFiles = (await readdir(textDir)).filter((name) => name.endsWith(".xml")).sort();
  const textEntries = await Promise.all(
    textFiles.map(async (name) => Bun.file(path.join(textDir, name)).text()),
  );
  const doc = parseSblgnt(textEntries.join("\n"));
  const realBcvs = new Set(doc.verses.map((v) => v.bcv));
  const failures = [...merged.keys()].filter((bcv) => !realBcvs.has(bcv));
  if (failures.length > 0) {
    throw new Error(
      `${failures.length} apparatus reference(s) do not resolve against the built text: ${failures.join(", ")}`,
    );
  }
  console.log(`  all ${merged.size} references resolve`);

  const entriesOut: readonly [string, readonly ApparatusNote[]][] = [...merged.entries()].sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  );

  const module = `// GENERATED by scripts/build-sblgnt-apparatus.ts — do not edit.
// A collation of printed editions (WH, Tregelles, NA27/NA28, RP, and
// occasionally others), not a manuscript apparatus — no papyri, uncials,
// minuscules or patristic citations. See src/sblgnt-apparatus.ts.

import type { ApparatusNote } from "../../sblgnt-apparatus.ts";

/** Verse coordinate ("JUD.1.5") -> that verse's apparatus notes. */
export const APPARATUS: Readonly<Record<string, readonly ApparatusNote[]>> = ${JSON.stringify(
    Object.fromEntries(entriesOut),
    null,
    2,
  )};
`;

  const outPath = new URL("../src/data/sblgnt/apparatus.ts", import.meta.url).pathname;
  await Bun.write(outPath, module);
  console.log(`Wrote src/data/sblgnt/apparatus.ts (${(module.length / 1024).toFixed(0)} KB)`);
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
