/**
 * Build step: turn an ebible.org USFX release into embedded TypeScript modules.
 *
 *   bun run build:data                      # the ASV, the default
 *   bun run build:data --translation dra    # once dra has a descriptor
 *
 * Emits four generated files under src/data/<translation>/:
 *   text.ts         verse text as one blob plus base36 delta-encoded lengths
 *   search-index.ts inverted index, token -> base36 delta-encoded postings
 *   families.ts     morphological families, derived from the vocabulary
 *   meta.ts         per-chapter verse counts, titles, notes, Hebrew offsets
 *
 * Writing under the edition's own directory is what stops one build from
 * overwriting another's corpus. The artifact *names* stay bare, so the
 * generation manifest hashes content rather than location and moving the
 * directory leaves both identifiers untouched.
 *
 * Nothing is written unless every assertion in src/validate.ts passes, against
 * the expectation set this edition declares in scripts/editions.ts.
 */

import { createHash } from "node:crypto";

import { parseUsfx, type UsfxDocument } from "../src/usfx.ts";
import { validateCorpus, ValidationError } from "../src/validate.ts";
import {
  archiveMember,
  archiveUrl,
  resolveEdition,
  type BuildEdition,
} from "./editions.ts";
import { EDITION_ORDER } from "../src/canon.ts";
import { buildFamilies } from "../src/morphology.ts";
import { tokenize } from "../src/tokenize.ts";
import { downloadWithResume, expectedSize, DownloadError } from "./download.ts";
import {
  CANONICAL_METADATA_VERSION,
  NORMALIZATION_POLICY_VERSION,
  PARSER_VERSION,
  SCHEMA_VERSION,
  canonicalJson,
  deriveGenerationId,
  deriveRevisionId,
  sha256,
  type ArtifactRecord,
  type GenerationManifest,
} from "../src/identity.ts";

/**
 * Which edition this run is building. Everything below reads from it rather
 * than from a constant, so a second text is an entry in scripts/editions.ts
 * instead of an edit here.
 */
const EDITION: BuildEdition = (() => {
  const index = process.argv.indexOf("--translation");
  try {
    return resolveEdition(index === -1 ? undefined : process.argv[index + 1]);
  } catch (error) {
    // Resolution happens at module load, before the handler around main(), so
    // an unknown id would otherwise surface as a stack trace rather than the
    // sentence naming what this build can produce.
    console.error(`\n${(error as Error).message}`);
    process.exit(1);
  }
})();

/** Report what the source contains without asserting or writing anything. */
const REPORT_ONLY = process.argv.includes("--report");

const SOURCE_URL = archiveUrl(EDITION);
const CACHE_DIR = new URL("../.cache/", import.meta.url).pathname;
const ZIP_PATH = `${CACHE_DIR}${EDITION.sourceId}_usfx.zip`;
const XML_PATH = `${CACHE_DIR}${archiveMember(EDITION)}`;
const DATA_DIR = new URL(`../src/data/${EDITION.id}/`, import.meta.url).pathname;

async function download(): Promise<void> {
  const existing = Bun.file(ZIP_PATH);
  const expected = await expectedSize(SOURCE_URL, fetch);
  if ((await existing.exists()) && existing.size === expected) {
    console.log(`  cached  ${expected.toLocaleString()} bytes`);
    return;
  }
  const bytes = await downloadWithResume(SOURCE_URL, {
    onProgress: (received, total, attempt) => {
      console.log(`  attempt ${attempt}: ${received.toLocaleString()} / ${total.toLocaleString()}`);
    },
  });
  await Bun.write(ZIP_PATH, bytes);
}

async function extract(): Promise<string> {
  const cached = Bun.file(XML_PATH);
  if (!(await cached.exists())) {
    const unzip = Bun.spawn(["unzip", "-o", "-q", ZIP_PATH, archiveMember(EDITION), "-d", CACHE_DIR], {
      stderr: "pipe",
    });
    const code = await unzip.exited;
    if (code !== 0) {
      throw new Error(`unzip failed with code ${code}: ${await new Response(unzip.stderr).text()}`);
    }
  }
  return await Bun.file(XML_PATH).text();
}

/** Base36 delta encoding keeps the numeric payloads compact in the bundle. */
function encodeDeltas(values: readonly number[]): string {
  let previous = 0;
  const parts: string[] = [];
  for (const value of values) {
    parts.push((value - previous).toString(36));
    previous = value;
  }
  return parts.join(",");
}

function buildTextModule(doc: UsfxDocument): string {
  const blob = doc.verses.map((verse) => verse.text).join("");
  const lengths = doc.verses.map((verse) => verse.text.length);
  return `// GENERATED by scripts/build-data.ts — do not edit.
/** Every verse concatenated in canonical order, addressed by LENGTHS offsets. */
export const TEXT: string = ${JSON.stringify(blob)};

/** Base36 delta-encoded verse lengths; cumulative sums give slice boundaries. */
export const LENGTHS: string = ${JSON.stringify(encodeDeltas(lengths))};

export const VERSE_COUNT = ${doc.verses.length};
`;
}

function buildIndexModule(doc: UsfxDocument): string {
  const postings = new Map<string, number[]>();
  doc.verses.forEach((verse, sequence) => {
    const seen = new Set<string>();
    for (const token of tokenize(verse.text)) {
      if (seen.has(token)) continue;
      seen.add(token);
      let list = postings.get(token);
      if (list === undefined) {
        list = [];
        postings.set(token, list);
      }
      list.push(sequence);
    }
  });

  const lines = [...postings.entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([token, list]) => `${token}:${encodeDeltas(list)}`);

  const wordCounts = doc.verses.map((verse) => (verse.text === "" ? 0 : verse.text.split(" ").length));

  const frequencies = [...postings.entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([, list]) => list.length);

  return `// GENERATED by scripts/build-data.ts — do not edit.
/** Inverted index: one "token:base36DeltaPostings" entry per line. */
export const INDEX: string = ${JSON.stringify(lines.join("\n"))};

/**
 * Base36 delta-encoded posting count per token, in the same order as INDEX.
 * Lets a query weigh a term without decoding its postings.
 */
export const DOC_FREQUENCIES: string = ${JSON.stringify(encodeDeltas(frequencies))};

/** Base36 delta-encoded word count per verse, for BM25 length normalization. */
export const WORD_COUNTS: string = ${JSON.stringify(encodeDeltas(wordCounts))};

export const TOKEN_COUNT = ${lines.length};
`;
}

/**
 * A short, stable fingerprint of the corpus. It names the edge cache, so
 * regenerating the data automatically invalidates cached responses instead of
 * letting an `immutable` Cache-Control serve last year's text after a redeploy.
 */
function fingerprint(doc: UsfxDocument): string {
  const hash = createHash("sha256");
  for (const verse of doc.verses) {
    hash.update(verse.bcv);
    hash.update("\u0000");
    hash.update(verse.text);
    hash.update("\u0000");
  }
  for (const [key, title] of [...doc.titles].sort(([a], [b]) => (a < b ? -1 : 1))) {
    hash.update(`${key}=${title}\u0000`);
  }
  return hash.digest("hex").slice(0, 12);
}

/**
 * Word families are a pure function of the vocabulary, so they are computed here
 * rather than on every isolate start. Building them at runtime measured 14 ms
 * locally and several times that in production, against a bundle cost of a few
 * tens of kilobytes.
 */
function buildFamiliesModule(tokens: readonly string[]): string {
  const families = buildFamilies(tokens);
  const groups = new Map<string, readonly string[]>();
  for (const [, family] of families) groups.set(family.join(","), family);
  const lines = [...groups.keys()].sort();
  return `// GENERATED by scripts/build-data.ts — do not edit.
/** Morphological families, one comma-separated group per line. */
export const FAMILY_GROUPS: string = ${JSON.stringify(lines.join("\n"))};

export const FAMILY_COUNT = ${lines.length};
`;
}

/** The identity block prepended to the generated metadata module. */
function buildIdentityBlock(manifest: GenerationManifest, generationId: string): string {
  return `// GENERATED by scripts/build-data.ts — do not edit.
/**
 * What the text is. Derived from the source archive alone, so republishing
 * artifacts over unchanged source leaves it untouched. Anchors bind to this.
 */
export const REVISION_ID = ${JSON.stringify(manifest.revisionId)};

/**
 * What was published. Derived from the whole manifest, so a metadata-only
 * change mints a new generation over identical text.
 */
export const GENERATION_ID = ${JSON.stringify(generationId)};

export const EDITION_ID = ${JSON.stringify(manifest.editionId)};

`;
}

function buildMetaModule(doc: UsfxDocument): string {
  const verseCounts = new Map<string, number[]>();
  for (const verse of doc.verses) {
    let chapters = verseCounts.get(verse.book);
    if (chapters === undefined) {
      chapters = [];
      verseCounts.set(verse.book, chapters);
    }
    chapters[verse.chapter - 1] = (chapters[verse.chapter - 1] ?? 0) + 1;
  }

  const countsLiteral = EDITION_ORDER[EDITION.id].map((bookId) => {
    const chapters = verseCounts.get(bookId);
    if (chapters === undefined) throw new Error(`No verses collected for ${bookId}`);
    return `  ${bookId.startsWith("1") || bookId.startsWith("2") || bookId.startsWith("3") ? `"${bookId}"` : bookId}: [${chapters.join(",")}],`;
  }).join("\n");

  const titlesLiteral = [...doc.titles.entries()]
    .map(([key, title]) => `  ${JSON.stringify(key)}: ${JSON.stringify(title)},`)
    .join("\n");

  const subscriptionsLiteral = [...doc.subscriptions.entries()]
    .map(([key, text]) => `  ${JSON.stringify(key)}: ${JSON.stringify(text)},`)
    .join("\n");

  const notesLiteral = doc.verses
    .filter((verse) => verse.note !== null)
    .map((verse) => `  ${JSON.stringify(verse.bcv)}: ${JSON.stringify(verse.note)},`)
    .join("\n");

  // A Psalm carrying a superscription numbers that title as Hebrew verse 1,
  // shifting every English verse up by one.
  const titledPsalms = [...doc.titles.keys()]
    .filter((key) => key.startsWith("PSA."))
    .map((key) => Number.parseInt(key.slice(4), 10))
    .sort((a, b) => a - b);

  return `// GENERATED by scripts/build-data.ts — do not edit.
/** Fingerprint of the corpus; changes whenever any verse or title changes. */
export const DATA_VERSION = ${JSON.stringify(fingerprint(doc))};

/** Verse count per chapter, indexed from chapter 1, for each of the 66 books. */
export const VERSE_COUNTS: Readonly<Record<string, readonly number[]>> = {
${countsLiteral}
};

/** Superscriptions printed above a chapter, keyed by "BOOK.CHAPTER". */
export const TITLES: Readonly<Record<string, string>> = {
${titlesLiteral}
};

/**
 * Lines printed below a chapter's last verse. USFX marks these with the same
 * <d> element as a superscription, so only position tells them apart.
 */
export const SUBSCRIPTIONS: Readonly<Record<string, string>> = {
${subscriptionsLiteral}
};

/** Footnotes for the verses the ASV omits from its text. */
export const NOTES: Readonly<Record<string, string>> = {
${notesLiteral}
};

/** Psalms whose superscription counts as Hebrew verse 1. */
export const TITLED_PSALMS: readonly number[] = [${titledPsalms.join(",")}];
`;
}

/**
 * What the source actually contains, printed rather than asserted.
 *
 * An edition cannot be characterised before it has been read, so this exists to
 * break that circle honestly: it reports, a person reads, and the expectation
 * set is authored from figures someone has looked at. Emitting the observations
 * straight into an expectation set would produce a gate that agrees with
 * whatever it was fed, which is worse than no gate because it looks like one.
 *
 * Nothing is written in this mode.
 */
function report(doc: UsfxDocument): void {
  const byBook = new Map<string, Map<number, number>>();
  for (const verse of doc.verses) {
    let chapters = byBook.get(verse.book);
    if (chapters === undefined) {
      chapters = new Map<number, number>();
      byBook.set(verse.book, chapters);
    }
    chapters.set(verse.chapter, (chapters.get(verse.chapter) ?? 0) + 1);
  }

  const sum = (bucket: ReadonlyMap<string, number>): number =>
    [...bucket.values()].reduce((total, n) => total + n, 0);
  const ledger = doc.ledger;
  const accounted =
    sum(ledger.toVerses) +
    sum(ledger.toTitles) +
    sum(ledger.toSubscriptions) +
    sum(ledger.toNotes) +
    sum(ledger.dropped) +
    ledger.unattributed;

  const empty = doc.verses.filter((verse) => verse.text === "").map((verse) => verse.bcv);
  const unbalanced = doc.verses
    .filter((verse) => {
      const opens = (verse.text.match(/\[/g) ?? []).length;
      const closes = (verse.text.match(/\]/g) ?? []).length;
      return opens !== closes;
    })
    .map((verse) => verse.bcv);

  console.log(`\nObserved in ${EDITION.id} (${EDITION.sourceId})`);
  console.log("─".repeat(52));
  console.log(`  verses          ${doc.verses.length.toLocaleString()}`);
  console.log(`  books           ${doc.books.length}`);
  console.log(`  superscriptions ${doc.titles.size}`);
  console.log(`  subscriptions   ${doc.subscriptions.size}${
    doc.subscriptions.size > 0 ? `  [${[...doc.subscriptions.keys()].join(", ")}]` : ""
  }`);
  console.log(`  verses w/ notes ${doc.verses.filter((verse) => verse.note !== null).length}`);
  console.log(`  empty verses    ${empty.length}${empty.length > 0 ? `  [${empty.join(", ")}]` : ""}`);
  console.log(
    `  unbalanced [ ]  ${unbalanced.length}${unbalanced.length > 0 ? `  [${unbalanced.join(", ")}]` : ""}`,
  );

  console.log("\n  coverage ledger");
  console.log(`    source        ${ledger.sourceCharacters.toLocaleString()}`);
  console.log(`    accounted     ${accounted.toLocaleString()}`);
  console.log(
    `    balance       ${accounted === ledger.sourceCharacters ? "exact" : `${ledger.sourceCharacters - accounted} unexplained`}`,
  );
  console.log(`    to verses     ${sum(ledger.toVerses).toLocaleString()}`);
  console.log(`    to titles     ${sum(ledger.toTitles).toLocaleString()}`);
  console.log(`    to subs       ${sum(ledger.toSubscriptions).toLocaleString()}`);
  console.log(`    to notes      ${sum(ledger.toNotes).toLocaleString()}`);
  console.log(`    unattributed  ${ledger.unattributed.toLocaleString()}`);

  console.log("\n  dropped as document furniture");
  for (const [element, count] of [...ledger.dropped].sort(([a], [b]) => (a < b ? -1 : 1))) {
    console.log(`    <${element}>`.padEnd(20) + String(count).padStart(10));
  }

  console.log("\n  books, in the order the source prints them");
  const order = EDITION_ORDER[EDITION.id];
  for (const [index, bookId] of doc.books.entries()) {
    const chapters = byBook.get(bookId);
    const verses = chapters === undefined ? 0 : [...chapters.values()].reduce((s, n) => s + n, 0);
    const expectedHere = order[index];
    const flag = expectedHere === bookId ? "  " : ` ← canon.ts expects ${expectedHere ?? "nothing"}`;
    console.log(
      `    ${String(index + 1).padStart(2)} ${bookId}  ` +
        `${String(chapters?.size ?? 0).padStart(3)} ch  ` +
        `${String(verses).padStart(5)} v${flag}`,
    );
  }

  console.log(`\nNothing written. Author src/expectations/${EDITION.id}.ts from the above.\n`);
}

async function main(): Promise<void> {
  console.log(`Building ${EDITION.id} (${EDITION.sourceId})`);
  console.log("Downloading USFX…");
  await download();

  console.log("Extracting…");
  const xml = await extract();

  console.log("Parsing…");
  const started = performance.now();
  const doc = parseUsfx(xml);
  console.log(
    `  ${doc.verses.length.toLocaleString()} verses, ${doc.books.length} books, ` +
      `${doc.titles.size} titles in ${(performance.now() - started).toFixed(0)} ms`,
  );

  if (REPORT_ONLY) {
    report(doc);
    return;
  }

  if (EDITION.expectations === undefined) {
    throw new Error(
      `${EDITION.id} has no expectation set, so there is nothing to validate ` +
        `it against and nothing will be written. Run with --report to see what ` +
        `the source contains, then author src/expectations/${EDITION.id}.ts ` +
        `from figures you have read rather than from whatever this run emitted.`,
    );
  }

  console.log("Validating…");
  validateCorpus(doc, EDITION.expectations);
  console.log("  all assertions passed");

  console.log("Building artifacts…");
  const textModule = buildTextModule(doc);
  const indexModule = buildIndexModule(doc);
  const metaBody = buildMetaModule(doc);

  // Families are derived from the vocabulary the index just recorded.
  const tokens = [...new Set(
    doc.verses.flatMap((verse) => tokenize(verse.text)),
  )].sort();
  const familiesModule = buildFamiliesModule(tokens);

  // Identity is computed over artifact *contents*, before anything is written.
  // Hashing the emitted meta.ts would be circular, since that file carries the
  // generation id the hash is meant to produce.
  console.log("Deriving identity…");
  const archiveBytes = new Uint8Array(await Bun.file(ZIP_PATH).arrayBuffer());
  const sourceArchive = {
    url: SOURCE_URL,
    sha256: await sha256(archiveBytes),
    byteLength: archiveBytes.byteLength,
  };
  const revisionId = deriveRevisionId(sourceArchive);

  const artifacts: ArtifactRecord[] = [];
  for (const [name, content] of [
    ["text.ts", textModule],
    ["search-index.ts", indexModule],
    ["families.ts", familiesModule],
    ["meta.ts", metaBody],
  ] as const) {
    artifacts.push({
      name,
      sha256: await sha256(content),
      byteLength: new TextEncoder().encode(content).byteLength,
    });
  }

  const manifest: GenerationManifest = {
    schemaVersion: SCHEMA_VERSION,
    parserVersion: PARSER_VERSION,
    normalizationPolicyVersion: NORMALIZATION_POLICY_VERSION,
    canonicalMetadataVersion: CANONICAL_METADATA_VERSION,
    editionId: EDITION.sourceId,
    revisionId,
    sourceArchive,
    artifacts,
    corpus: {
      verses: doc.verses.length,
      books: doc.books.length,
      superscriptions: doc.titles.size,
      subscriptions: doc.subscriptions.size,
      notes: doc.verses.filter((verse) => verse.note !== null).length,
    },
  };
  const generationId = await deriveGenerationId(manifest);
  console.log(`  revision   ${revisionId.slice(0, 16)}…`);
  console.log(`  generation ${generationId.slice(0, 16)}…`);

  console.log("Emitting data modules…");
  await Bun.write(`${DATA_DIR}text.ts`, textModule);
  await Bun.write(`${DATA_DIR}search-index.ts`, indexModule);
  await Bun.write(`${DATA_DIR}families.ts`, familiesModule);
  await Bun.write(`${DATA_DIR}meta.ts`, buildIdentityBlock(manifest, generationId) + metaBody);

  // The manifest is committed so a reader can see what a generation is made of
  // without rebuilding it, and so a drift in identity is visible in a diff.
  //
  // One per edition. A single file at the root meant the second build silently
  // replaced the first edition’s record with its own — the artifacts were
  // already safe under src/data/<id>/, but their manifest was not.
  await Bun.write(
    `${DATA_DIR}manifest.json`,
    `${canonicalJson({ ...manifest, generationId })}\n`,
  );

  // The lossy inventory: what the parser dropped, and how much of it.
  const lossy = Object.fromEntries(
    [...doc.ledger.dropped].sort(([a], [b]) => (a < b ? -1 : 1)),
  );
  console.log("Dropped as document furniture (characters):");
  for (const [element, count] of Object.entries(lossy)) {
    console.log(`  <${element}>`.padEnd(20) + String(count).padStart(8));
  }

  for (const name of ["text.ts", "search-index.ts", "meta.ts", "families.ts"]) {
    const file = Bun.file(`${DATA_DIR}${name}`);
    console.log(`  src/data/${EDITION.id}/${name.padEnd(16)} ${(file.size / 1024 / 1024).toFixed(2)} MB`);
  }
}

try {
  await main();
} catch (error) {
  if (error instanceof ValidationError) {
    console.error(`\nIngestion aborted. ${error.message}`);
  } else if (error instanceof DownloadError) {
    console.error(`\nIngestion failed while downloading: ${error.message}`);
  } else {
    console.error(`\nIngestion failed: ${(error as Error).message}`);
  }
  process.exit(1);
}
