/**
 * Embeds openapi.yaml as a TypeScript module so the Worker can serve it.
 *
 * A Worker has no filesystem, and bundler-specific text imports behave one way
 * under wrangler and another under `bun test`, which would let the spec the
 * tests check and the spec the API serves drift apart. A generated module
 * behaves identically everywhere.
 *
 * openapi.yaml stays the source of truth. src/openapi.ts is generated from it,
 * and src/contract.test.ts fails if the two ever disagree.
 */
const yaml = await Bun.file(new URL("../openapi.yaml", import.meta.url)).text();

const module = `// GENERATED by scripts/embed-openapi.ts — do not edit.
// Source of truth is openapi.yaml at the repository root.

/** The published contract, served at /openapi.yaml. */
export const OPENAPI: string = ${JSON.stringify(yaml)};
`;

await Bun.write(new URL("../src/openapi.ts", import.meta.url).pathname, module);
console.log(`Embedded openapi.yaml (${yaml.length.toLocaleString()} chars) -> src/openapi.ts`);
