/**
 * Keeps the published contract from drifting away from the running code.
 *
 * `openapi.yaml` is the first thing an integrating developer reads and often
 * the only thing their generated client knows. It had already drifted: the
 * translation id was declared `enum: [asv]` while the API was answering for
 * `dra`, so a client generated from the spec would have rejected a valid
 * response. That is the kind of failure nobody notices from inside.
 *
 * These assert the parts of the document that make claims about behaviour. The
 * prose is left alone; `bun run check:contract` validates real responses
 * against the schemas, and this covers what a static document can be wrong
 * about on its own.
 */
import { describe, expect, test } from "bun:test";
import app from "./index.ts";
import { TRANSLATION_IDS } from "./translations.ts";
import { OPENAPI } from "./openapi.ts";

const SPEC = await Bun.file(new URL("../openapi.yaml", import.meta.url)).text();

describe("openapi.yaml describes the API that exists", () => {
  test("the translation enum lists exactly what the registry serves", () => {
    const match = SPEC.match(/id:\s*\{\s*type:\s*string,\s*enum:\s*\[([^\]]+)\]/);
    expect(match).not.toBeNull();
    const declared = match![1]!.split(",").map((id) => id.trim()).sort();
    expect(declared).toEqual([...TRANSLATION_IDS].sort());
  });

  test("every documented path is a route that answers", async () => {
    const paths = [...SPEC.matchAll(/^ {2}(\/[A-Za-z0-9{}/_.-]*):$/gm)].map((m) => m[1]!);
    expect(paths.length).toBeGreaterThan(4);
    for (const path of paths) {
      // Fill path templates with values that exist, so a 404 means the route is
      // missing rather than the example being wrong.
      const probe = path.replace("{id}", "GEN").replace("{num}", "1");
      const query = probe === "/passages" ? "?ref=John+3:16" : probe === "/search" ? "?q=shepherd" : "";
      const response = await app.fetch(new Request(`https://colophon.test${probe}${query}`));
      expect({ path, status: response.status }).toEqual({ path, status: 200 });
    }
  });

  test("the spec is reachable from the API it documents", async () => {
    const response = await app.fetch(new Request("https://colophon.test/openapi.yaml"));
    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toContain("yaml");
    expect(await response.text()).toBe(SPEC);
  });

  test("the embedded copy has not drifted from the file", () => {
    // src/openapi.ts is generated by scripts/embed-openapi.ts. If this fails,
    // openapi.yaml was edited without re-running `bun run build:openapi`, and
    // the API is serving a contract that is not the one in the repository.
    expect(OPENAPI).toBe(SPEC);
  });

  test("it does not still describe itself as one translation", () => {
    expect(SPEC).not.toContain("The complete American Standard Version (1901), public domain");
  });
});
